version: 2
jobs:
  build:
    environment:
      - TZ: "/usr/share/zoneinfo/GMT"

    docker:
      - image: circleci/node:6.10.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
        keys:
           - v0-ci-pkg-{{ checksum ".circleci/package-lock.json" }}
           - v0-ci-pkg

      - run: npm install

      - save_cache:
          key: v0-ci-pkg-{{ checksum ".circleci/package-lock.json" }}
          paths:
            - .circleci/node_modules

      - run: npm run lint

      - run: npm run test
